version: 2

builds:
  - id: linux_amd64
    goos:
      - linux
    goarch:
      - amd64
    binary: "{{ .ProjectName }}_Linux_x86_64"

  - id: linux_arm64
    goos:
      - linux
    goarch:
      - arm64
    binary: "{{ .ProjectName }}_Linux_arm64"

  - id: windows_amd64
    goos:
      - windows
    goarch:
      - amd64
    binary: "{{ .ProjectName }}_Windows_x86_64"

  - id: windows_arm64
    goos:
      - windows
    goarch:
      - arm64
    binary: "{{ .ProjectName }}_Windows_arm64"

  - id: macos_amd64
    goos:
      - darwin
    goarch:
      - amd64
    binary: "{{ .ProjectName }}_macOS_x86_64"

  - id: macos_arm64
    goos:
      - darwin
    goarch:
      - arm64
    binary: "{{ .ProjectName }}_macOS_arm64"

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - linux_amd64
      - linux_arm64
      - macos_amd64
      - macos_arm64

  - id: windows
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - windows_amd64
      - windows_arm64

brews:
  - repository:
      owner: gambithunt
      name: homebrew-tools
      branch: main
    homepage: "https://github.com/gambithunt/homebrew-tools"
    description: "A tool to convert terminal configs to Ghostty"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
