version: 2

builds:
  - id: linux_amd64
    goos:
      - linux
    goarch:
      - amd64
    name_template: "{{ .ProjectName }}_Linux_x86_64"

  - id: linux_arm64
    goos:
      - linux
    goarch:
      - arm64
    name_template: "{{ .ProjectName }}_Linux_arm64"

  - id: windows_amd64
    goos:
      - windows
    goarch:
      - amd64
    name_template: "{{ .ProjectName }}_Windows_x86_64"
    archive:
      format: zip

  - id: windows_arm64
    goos:
      - windows
    goarch:
      - arm64
    name_template: "{{ .ProjectName }}_Windows_arm64"
    archive:
      format: zip

  - id: macos_amd64
    goos:
      - darwin
    goarch:
      - amd64
    name_template: "{{ .ProjectName }}_macOS_x86_64"

  - id: macos_arm64
    goos:
      - darwin
    goarch:
      - arm64
    name_template: "{{ .ProjectName }}_macOS_arm64"

archives:
  - id: default
    format: tar.gz
    builds:
      - linux_amd64
      - linux_arm64
      - macos_amd64
      - macos_arm64
  - id: windows
    format: zip
    builds:
      - windows_amd64
      - windows_arm64